### ISSUE TITLE
Errors if software is not installed.

### ISSUE THREAD

**Issue by Jacxk** [gooday2die/PyPheperial#1]
This works great. I love it.

But there is an issue when running the script and you don't have Razer's RGB software. It tried to make an HTTP request but since the software is not installed it times out and the program doesn't run.

I had to `try` and `except` all requests functions inside the Razer script, so I don't run into that issue, since I only have a Corsair mice.

Could you maybe make it so if it doesn't detect the Razer's software it will skip it and not use the corresponding method?

**Comment by isu-kim** [comment]
I am so so sorry that I did not think anyone would be using this script and manage to open an issue. I will definitely modify that one as soon as possible. Again Sorry for so late reply :(

**Comment by rosshiga** [comment]
> I am so so sorry that I did not think anyone would be using this script and manage to open an issue. I will definitely modify that one as soon as possible. Again Sorry for so late reply :(

You're doing good work out there. Looking forward to using your code once I get my Corsair build going!!

**Comment by isu-kim** [comment]
Thanks for the support everyone! I have some good news here. I have developed AllPheripherals project which is better in terms of performance and efficiency. Also, the Error due to Razer Chroma `try `and `except `would be gone in that project since I am using a DLL with C++ based program. Please check the link https://github.com/gooday2die/AllPeripherals here.

**Comment by isu-kim** [comment]
Hello, my huge apologies for not updating this project for a long time. I live in South Korea, where I must spend time in the army for a year and half. Also I was not able to update this project since I had no access to my PC. However, I got a bit of access to my PC recent days and now am updating this project.

In short, I have updated the project for ease of use. (Also back in 2020 and 2019, I was a noob at programming than now) I refactored most of the program and worked on OOP style codes so that more people can Pull Request, or access the code more easily. 

From now on, you can install this project by `pip install PyPeripheral`. Also for Razer, I have made some exception control over the Wrapper, so that you would not have to worry about the program any more. (I might have missed some since I do not have Razer devices, if there are bugs and isses, please let me know)

I am sorry for making everybody wait for a whole 3 years, and I will be providing support for this project as much as possible. 
Thank you
